version: "3"
services:
  db:
    container_name: cashcontroldb
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: my_p4ssword3322
      POSTGRES_DB: cashcontrol
    ports:
      - 5432:5432
    networks:
      - app-network
  api:
    container_name: api
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - 80:5200
    depends_on:
      - db
    command: ./wait-for.sh db:27017 -- ./init.sh
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
